networks:
  web:
    external: true
  internal:
    external: false
services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.network=internal"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.myresolver.tailscale=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks:
      - web
      - internal
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    # container-name: "simle-service"
    # networks:
    #   - traefik
    labels:
      # - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.skogix.unicorn-morpho.ts.net`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      # - "traefik.enable=true"
