github.com:
    users:
        Skogix:
            oauth_token: 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
    git_protocol: https
    user: Skogix
    oauth_token: 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
